SELECT DISTINCT
--CPRO Customer Complaint by XYZ (BHR) - V2 2010Nov10
--09 Nov 2010 sniegocki, replace QSI_CATEGORY_LOOKUP with QSI_CATEGORY_LOOKUP_TBL
--ALL FROM Customer Complaint Requests to CARS & SCARS

--Customer Complaint Document

--CC General Document Information
--REQ.QSI_ORGKEY "GDISID",--REQUEST
--REQ.QSI_UNIQUEID AS UNIQUEID, 
--REQ.QSI_FAMILYID AS FAMILYID,
--REQ.QSI_FBSCHEMA AS FBSCHEMA,
--REQ.QSI_DCLASSKEY AS CLASS,
--REQ.QSI_DTYPEKEY AS DOCTYPE,
REQ.QSI_CONTROLNUM AS "CC Req Number",--REQUEST

REQ.QSI_STATUS AS "CC Req Status",--REQUEST
REQ.QSI_URL "CC Req URL",
REQ.QSI_ORGKEY AS "CC Req GDIS",--REQUEST
REQ.QSI_ORGVALUE "CC Req Dana Location",--REQUEST
--REQ.QSI_CONTROLNUM AS CONTROLNUM,--REQUEST
REQ.QSI_CREDATE "CC Req Create Date",--REQUEST
REQ.QSI_DUEDATE "CC Req Due Date",--REQUEST
REQ.QSI_CLOSEDATE "CC Req Close Date",--REQUEST
REQ.QSI_APPDATE "CC Req Approve Date",--REQUEST
REQ.QSI_EFREVDATE "CC Req Effive Date", -- fixed in 7.4
REQ.QSI_DOCEXPEDITER "CC Req Author",
REQ.QSI_TITLE "CC Req Title",--REQUEST

DEG.SEVERITY "CC Req Concern Severity", --REQUEST SEVERITY
DEG.STOPSHIP "CC Req Stop Ship", --STOP SHIP
DEG.REPEATISSUE "CC Req Repeat Issue", -- Repeat Issue

--THIS IS IDENTIFYING THE 4 LEVELS OF THE PRODUCT PROBLEM CATEGORY
--CAT1.QSI_CHOICENAME "Problem Category 1", -- PRODUCT PROBLEM CATEGORY LEVEL 1
--CAT2.QSI_CHOICENAME "Problem Category 2", -- PRODUCT PROBLEM CATEGORY LEVEL 2
--CAT3.QSI_CHOICENAME "Problem Category 3", -- PRODUCT PROBLEM CATEGORY LEVEL 3
--CAT4.QSI_CHOICENAME "Problem Category 4", -- PRODUCT PROBLEM CATEGORY LEVEL 3
--THIS IS IDENTIFYING THE 4 LEVELS OF THE PART CATEGORY
--CAT5.QSI_CHOICENAME "Part Category 1", -- PRODUCT PROBLEM CATEGORY LEVEL 1
--CAT6.QSI_CHOICENAME "Part Category 2", -- PRODUCT PROBLEM CATEGORY LEVEL 2
--CAT7.QSI_CHOICENAME "Part Category 3", -- PRODUCT PROBLEM CATEGORY LEVEL 3
--CAT8.QSI_CHOICENAME "Part Category 4", -- PRODUCT PROBLEM CATEGORY LEVEL 3

DEG.PARTUSE "CC Req Part Used", --REQUEST Part use
DEG.DISPUTED "CC Req Disputed", -- Disputed
-- nned product group problem code
DEG.PRODGRPPROBCODE "CC Req Prod Grp Prob Code", -- 
-- need CAR responsibility
DEG.CARRESP "CC Req CAR Resp", -- 

IC1.QSI_VALUE "CC Req Basic Problem", -- JOINING FROM THE QSI-CC_QY_VIEW

CCCHK.INITIALREJECTQTY "CC Req Initial Reject Qty", --INITIAL REJECT QUANTITY
--THIS IS PULLING FROM THE DANA CCREQCHKLIST
CCCHK.CUSTOMERPARTNO "CC Req Customer Part No.", --cust part number
HMDCUST.QSI_TITLE "CC Req Customer Name", --CUSTOMER NAME FROM HMD
--HMDPROD.QSI_TITLE "PART NAME", -- hosted master product data
--ALL HOSTED MASTER DATA INFO
HMDPROD.QSI_REFNUM "CC Req Part Number",
HMDPROD.QSI_NAME "CC Req Part Name",
HMDPROD.QSI_TEXT1 "CC Req Part Revision",
HMDPROD.QSI_TEXT2 "CC Req Part Serial No.",
HMDPROD.QSI_TEXT3 "CC Req Part Traceability",
HMDPROD.QSI_TEXT4 "CC Req Part Usage",
--HMDPROD.QSI_TITLE AS PARTNAME, -- hosted master product data
--HMDCUST.QSI_TITLE "CUSTOMER NAME", --CUSTOMER NAME FROM HMD
HMDCUST1.QSI_TEXT8 "CC Req PARENT NAME", -- CUSTOMER PARENT NAME FROM HMD

--Customer Complaint Response Document

CCCHKRS.FINALREJECTQTY "CC Res Final Reject Qty",  --FINAL REJECT QUANTITY
--PULLING FROM DANA CC RSP COSTS VIEW (RESPONSE)

CCOST.LABORTIME "CC Res Labor Time",
CCOST.DOWNTIME "CC Res Down Time",
CCOST.INTERNALCOSTS "CC Res Internal Costs",
CCOST.CUSTOMERCHARGEBACK "CC Res Customer Charge Back",
CCOST.PREMIUMFREIGHT "CC Res Premium Freight",
RS.qsi_CREDATE "CC Res Create Date",
RS.qsi_DUEDATE "CC Res Due Date",
RS.qsi_CLOSEDATE "CC Res Close Date",
RS.qsi_STATUS "CC Res Status",
RS.qsi_DOCEXPEDITER "CC Res Assignee",
RS.qsi_URL "CC Res URL Link",

--CAR Request
CAREQ.QSI_CONTROLNUM "CAR Req Number",--IS THERE A CAR - ASSOCAITED ITEM STUFF
CAREQ.QSI_STATUS "CAR Req Status",--REQUEST
CAREQ.QSI_URL "CAR Req URL Link",
CAREQ.QSI_DOCEXPEDITER "CAR Req Assignee",
CAREQ.QSI_CREDATE "CAR Req CREATE DATE",--REQUEST
CAREQ.QSI_DUEDATE "CAR Req DUE DATE",--REQUEST
CAREQ.QSI_CLOSEDATE "CAR Req CLOSE DATE",--REQUEST
CAREQ.QSI_APPDATE "CAR Req Approve Date",--REQUEST
CAREQ.QSI_EFREVDATE "CAR Req Effive Date", -- fixed in 7.4
--CAR ST Response
CASTRES.QSI_CONTROLNUM "CAR ST Req Number",--IS THERE A CAR - ASSOCAITED ITEM STUFF
CASTRES.QSI_STATUS "CAR ST Req Status",--REQUEST
CASTRES.QSI_URL "CAR ST URL",
CASTRES.QSI_DOCEXPEDITER "CAR ST Req Assignee",
CASTRES.QSI_CREDATE "CAR ST Res CREATE DATE",--ST Car Response
CASTRES.QSI_DUEDATE "CAR ST Res DUE DATE",--ST Car Response
CASTRES.QSI_CLOSEDATE "CAR ST Res CLOSE DATE",--ST Car Response
CASTRES.QSI_APPDATE "CAR ST Res Approve Date",--ST Car Response
--CAR LT Response
CALTRES.QSI_CONTROLNUM "CAR LT Req Number",--IS THERE A CAR - ASSOCAITED ITEM STUFF
CALTRES.QSI_STATUS "CAR LT Req Status",--REQUEST
CALTRES.QSI_URL "CAR LT URL",
CALTRES.QSI_DOCEXPEDITER "CAR LT Req Assignee",
CALTRES.QSI_CREDATE "CAR LT Res CREATE DATE",--LT Car Response
CALTRES.QSI_DUEDATE "CAR LT Res DUE DATE",--LT Car Response
CALTRES.QSI_CLOSEDATE "CAR LT Res CLOSE DATE",--LT Car Response
CALTRES.QSI_APPDATE "CAR LT Res Approve Date",--LT Car Response
--SCAR Request
SCREQ.QSI_UNIQUEID,
SCREQ.QSI_CONTROLNUM "SCAR Req Number",--IS THERE A SCAR - ASSOCIAGTED ITEM STUFF
SCREQ.QSI_STATUS "SCAR Req Status",
SCREQ.QSI_URL "SCAR Req URL Link",
SCREQ.QSI_DOCEXPEDITER "SCAR Req Assignee",
SCREQ.QSI_CREDATE "SCAR Req CREATE DATE",--REQUEST
SCREQ.QSI_DUEDATE "SCAR Req DUE DATE",--REQUEST
SCREQ.QSI_CLOSEDATE "SCAR Req CLOSE DATE",--REQUEST
SCREQ.QSI_APPDATE "SCAR Req Approve Date",--REQUEST
SCREQ.QSI_EFREVDATE "SCAR Req Effive Date", -- fixed in 7.4
--SCAR Response
SCLTRES.QSI_CONTROLNUM "SCAR Res Number",--IS THERE A SCAR - ASSOCIAGTED ITEM STUFF
SCLTRES.QSI_STATUS "SCAR Res Status",
SCLTRES.QSI_URL "SCAR Res URL Link",
SCLTRES.QSI_DOCEXPEDITER "SCAR Res Assignee",
SCLTRES.QSI_CREDATE "SCAR Res CREATE DATE",--REQUEST
SCLTRES.QSI_DUEDATE "SCAR Res DUE DATE",--REQUEST
SCLTRES.QSI_CLOSEDATE "SCAR Res CLOSE DATE",--REQUEST
SCLTRES.QSI_APPDATE "SCAR Res Approve Date" --REQUEST

FROM (SELECT * FROM QSI_CC_MAIN where QSI_DTYPEKEY='qsi_WorkflowParameters51139') REQ --request
   LEFT OUTER JOIN QSI_CC_MAIN RS ON -- short term response
   	REQ.QSI_UNIQUEID =  RS.QSI_RQUID and RS.QSI_DTYPEKEY='qsi_WorkflowParameters98299' -- first response key
   
--JOIN TO GET THE BASIC PROBLEM CODE KEY AND LITERAL
 LEFT OUTER JOIN FB_QSI_CC_QY CCQY1 on -- THIS IS THE JOIN FOR THE BASIC PROBLEM CODE (returns only the key)
REQ.QSI_UNIQUEID = CCQY1.FFQSI_UNIQUE_ID and CCQY1.FFQSI_BASIC_PROBLEM_CODE is not null

 --JOINING TO GET THE 4 LEVELS OF THE PRODUCT PROBLEM CAGTEOGRY DEG
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT1 ON
--	CAT1.QSI_UNIQUEID = REQ.QSI_UNIQUEID and CAT1.QSI_GROUPKEY = 'qsi_Keywords47269' --PRODUCT PROBLEM CATEGORY LEVEL 1
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT2 on -- PRODUCT PROBLEM CATEGORY LEVEL 2
--	REQ.QSI_UNIQUEID = CAT2.QSI_UNIQUEID and CAT2.QSI_GROUPKEY = CAT1.QSI_CHOICEKEY
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT3 on -- PRODUCGT PROBLEM CATEGORY LEVEL 3
--	REQ.QSI_UNIQUEID = CAT3.QSI_UNIQUEID and CAT3.QSI_GROUPKEY = CAT2.QSI_CHOICEKEY
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT4 on -- PRODUCT PROBLEM CATEGORY LEVEL 4
--	REQ.QSI_UNIQUEID = CAT4.QSI_UNIQUEID and CAT4.QSI_GROUPKEY = CAT3.QSI_CHOICEKEY

--JOINING TO GET THE 4 LEVELS OF THE PRODUCT CAGTEOGRY DEG

--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT5 ON
--	CAT1.QSI_UNIQUEID = REQ.QSI_UNIQUEID and CAT5.QSI_GROUPKEY = 'qsi_Keywords55178' -- PRODUCT  CATEGORY LEVEL 1
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT6 on -- PRODUCT CATEGORY LEVEL 2
--	REQ.QSI_UNIQUEID = CAT6.QSI_UNIQUEID and CAT6.QSI_GROUPKEY = CAT5.QSI_CHOICEKEY
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT7 on -- PRODUCGT CATEGORY LEVEL 3
--	REQ.QSI_UNIQUEID = CAT7.QSI_UNIQUEID and CAT7.QSI_GROUPKEY = CAT6.QSI_CHOICEKEY
--LEFT OUTER JOIN QSI_CATEGORY_LOOKUP_TBL CAT8 on -- PRODUCT CATEGORY LEVEL 4
--	REQ.QSI_UNIQUEID = CAT8.QSI_UNIQUEID and CAT8.QSI_GROUPKEY = CAT7.QSI_CHOICEKEY


 LEFT OUTER JOIN QSI_INFOCAT_LOOKUP IC1 on -- THIS JOIN NOW MAKES THE BASIC PROBLEM CODE LITERAL
IC1.QSI_KEY = CCQY1.FFQSI_BASIC_PROBLEM_CODE and IC1.QSI_LANG = 'qsi_default' -- always use alias when more than one of the same.  'qsi_lang' used again in join below. 

--JOIN FOR COSTS ON RESPONSE
LEFT OUTER JOIN DANA_CC_RSP_COSTS CCOST ON
RS.QSI_UNIQUEID = CCOST.QSI_UNIQUEID

--JOIN FOR MASTER DATA

LEFT OUTER JOIN QSI_PRODMD_LOOKUP HMDPROD ON  -- HMD product join
  REQ.QSI_UNIQUEID = HMDPROD.QSI_HUNIQUEID  

LEFT OUTER JOIN QSI_CUSTMD_LOOKUP HMDCUST ON -- HMD CUSTOMER NAME
REQ.QSI_UNIQUEID = HMDCUST.QSI_HUNIQUEID
   
LEFT OUTER JOIN QSI_CUSTMD_LOOKUP HMDCUST1 ON -- HMD CUSTOMER PARENT NAME
REQ.QSI_UNIQUEID = HMDCUST1.QSI_HUNIQUEID

--JOIN TO THE DANA DEG VALUE VIEW
  LEFT OUTER JOIN DANA_DEG_VALUES DEG ON --ALL DEGS
   	REQ.QSI_UNIQUEID = 	DEG.QSI_UNIQUEID 

--JOIN TO THE DANA_CC_CHKLIST VIEW FOR REQUEST
   LEFT OUTER JOIN DANA_CC_CHKLIST CCCHK ON  -- CHECKLIST VALUES
REQ.QSI_UNIQUEID = CCCHK.QSI_UNIQUEID

--JOIN THE DANA_CC_CHKLIST VIEW FOR RESPONSE
  LEFT OUTER JOIN DANA_CC_CHKLIST CCCHKRS ON  
RS.QSI_UNIQUEID = CCCHKRS.QSI_UNIQUEID

--JOIN TO ASSOCIATED ITEMS/INDEPEDENT ITEMS
LEFT OUTER JOIN QSI_CA_MAIN CAREQ ON -- IS THERE CAR CREATED FROM THE CC?
RS.QSI_UNIQUEID = CAREQ.QSI_PROGENUID AND CAREQ.QSI_DTYPEKEY='qsi_WorkflowParameters18404'
LEFT OUTER JOIN QSI_CA_MAIN CASTRES ON -- short term response
CAREQ.QSI_UNIQUEID = CASTRES.QSI_RQUID AND CASTRES.QSI_DTYPEKEY='qsi_WorkflowParameters80853' -- first response key
LEFT OUTER JOIN QSI_CA_MAIN CALTRES ON -- short term response
CAREQ.QSI_UNIQUEID = CALTRES.QSI_RQUID AND CALTRES.QSI_DTYPEKEY='qsi_WorkflowParameters10221' -- first response key

LEFT OUTER JOIN QSI_SC_MAIN SCREQ ON  -- IS THERE A iSCAR CREATED FROM THE CC?
RS.QSI_UNIQUEID = SCREQ.QSI_PROGENUID AND SCREQ.QSI_DTYPEKEY='qsi_WorkflowParameters61563'
LEFT OUTER JOIN QSI_SC_MAIN SCLTRES ON -- short term response
SCREQ.QSI_UNIQUEID = SCLTRES.QSI_RQUID AND SCLTRES.QSI_DTYPEKEY='qsi_WorkflowParameters92474' -- first response key
