--DROP VIEW CPRO_STG.QSI_SU_MD_LOOKUP;

--CREATE OR REPLACE VIEW CPRO_STG.QSI_SU_MD_LOOKUP
--AS 
SELECT	 --8.5			
QYTBL.FFQSI_HOST_UNIQUE_ID QSI_HUNIQUEID, 			
QYTBL.FFQSI_SOURCE_UNIQUE_ID QSI_SUNIQUEID,			
QYTBL.FFQSI_HOST_FAMILY_ID QSI_HFAMILYID,			
QYTBL.FFQSI_HOST_VERSION QSI_HVERSION,			
QYTBL.FFQSI_SOURCE_FAMILY_ID QSI_SFAMILYID,			
QYTBL.FFQSI_SOURCE_VERSION QSI_SVERSION,			
QYTBL.FFQSI_MDX_DOCUMENT_ID QSI_MDXDOCID,			
QYTBL.FFQSI_REFERENCE_ID_NUMBER QSI_REFNUM,			
ITMTBL.FFQSI_DOC_CLASS_KEY QSI_DCLASSKEY,			
ITMTBL.FFQSI_DOC_TYPE_KEY QSI_DTYPEKEY,			
ITMTBL.FFQSI_TITLE QSI_TITLE,			
ITMTBL.FFQSI_CONTROL_NUMBER QSI_CONTROLNUM,			
QYTBL.FFQSI_SEQUENCE_NUMBER QSI_SEQNUM,				
CASE QYTBL.FFQSI_ORDER_NUMBER				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ORDER_NUMBER				
ELSE QYTBL.FFQSI_ORDER_NUMBER			
END QSI_ORDERNUM,			
CASE QYTBL.FFQSI_LOT_NUMBER				
WHEN 'qsi_smdref' 
THEN MDTBL.FFQSI_LOT_NUMBER				
ELSE QYTBL.FFQSI_LOT_NUMBER			
END QSI_LOTNUM,			
CASE QYTBL.FFQSI_LOT_SIZE				
WHEN -2147483647 
THEN MDTBL.FFQSI_LOT_SIZE				
ELSE QYTBL.FFQSI_LOT_SIZE			
END QSI_LOTSIZE,			
CASE QYTBL.FFQSI_SAMPLE_SIZE				
WHEN -2147483647 THEN MDTBL.FFQSI_SAMPLE_SIZE				
ELSE QYTBL.FFQSI_SAMPLE_SIZE			
END QSI_SMPLSIZE,			
CASE QYTBL.FFQSI_UNITS				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_UNITS				
ELSE QYTBL.FFQSI_UNITS			
END QSI_UNITS,			
CASE QYTBL.FFQSI_COST				
WHEN -2147483647 THEN MDTBL.FFQSI_COST				
ELSE QYTBL.FFQSI_COST			
END QSI_COST,			
CASE QYTBL.FFQSI_DATE				
WHEN TO_DATE('19000101','yyyymmdd') THEN MDTBL.FFQSI_DATE				
ELSE QYTBL.FFQSI_DATE			
END QSI_DATE,			
CASE QYTBL.FFQSI_DATE_CONVERTED				
WHEN TO_DATE('19000101','yyyymmdd') THEN MDTBL.FFQSI_DATE_CONVERTED				
ELSE QYTBL.FFQSI_DATE_CONVERTED			
END QSI_DATECONV,			
CASE QYTBL.FFQSI_DISPLAY_NAME				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_DISPLAY_NAME				
ELSE QYTBL.FFQSI_DISPLAY_NAME			
END QSI_NAME,					
CASE QYTBL.FFQSI_DISTINGUISHED_NAME				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_DISTINGUISHED_NAME				
ELSE QYTBL.FFQSI_DISTINGUISHED_NAME			
END QSI_DN,			
CASE QYTBL.FFQSI_FULL_NAME				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_FULL_NAME				
ELSE QYTBL.FFQSI_FULL_NAME			
END QSI_CN,			
CASE QYTBL.FFQSI_ADDITIONAL_TEXT1				
WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT1				
ELSE QYTBL.FFQSI_ADDITIONAL_TEXT1			
END QSI_TEXT1,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT2				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT2				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT2			END QSI_TEXT2,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT3				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT3				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT3			END QSI_TEXT3,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT4				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT4				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT4			END QSI_TEXT4,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT5				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT5				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT5			END QSI_TEXT5,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT6				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT6				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT6			END QSI_TEXT6,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT7				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT7				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT7			END QSI_TEXT7,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT8				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT8				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT8			END QSI_TEXT8,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT9				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT9				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT9			END QSI_TEXT9,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT10				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT10				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT10			END QSI_TEXT10,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT11				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT11				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT11			END QSI_TEXT11,			CASE QYTBL.FFQSI_ADDITIONAL_TEXT12				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_ADDITIONAL_TEXT12				ELSE QYTBL.FFQSI_ADDITIONAL_TEXT12			END QSI_TEXT12,	 		CASE QYTBL.FFQSI_DESCRIPTION1				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_DESCRIPTION1				ELSE QYTBL.FFQSI_DESCRIPTION1			END QSI_DESC1,			CASE QYTBL.FFQSI_DESCRIPTION2				WHEN 'qsi_smdref' THEN MDTBL.FFQSI_DESCRIPTION2				ELSE QYTBL.FFQSI_DESCRIPTION2			END QSI_DESC2		FROM 				FB_QSI_MASTER_DATA_INDEX_QY QYTBL		INNER JOIN  FB_QSI_ITEM_INDEX_QY ITMTBL ON 			QYTBL.FFQSI_SOURCE_UNIQUE_ID = ITMTBL.FFQSI_UNIQUE_ID AND			ITMTBL.FFQSI_DOC_CLASS_KEY = 'qsi_SU'			LEFT JOIN FB_QSI_MASTER_DATA_INDEX_QY MDTBL ON 			QYTBL.FFQSI_HOST_UNIQUE_ID = MDTBL.FFQSI_SOURCE_UNIQUE_ID AND 			MDTBL.FFQSI_SEQUENCE_NUMBER = -1		

--DROP VIEW CPRO_STG.QSI_SUPMD_LOOKUP;

--CREATE OR REPLACE VIEW CPRO_STG.QSI_SUPMD_LOOKUP
--AS 
SELECT 	  --8.1		
QYTBL.QSI_HUNIQUEID,			
QYTBL.QSI_SUNIQUEID,			
QYTBL.QSI_HFAMILYID,			
QYTBL.QSI_HVERSION,			
QYTBL.QSI_SFAMILYID,			
QYTBL.QSI_SVERSION,			
QYTBL.QSI_MDXDOCID,			
QYTBL.QSI_REFNUM,			
QYTBL.QSI_DTYPEKEY,			
QYTBL.QSI_TITLE,			
QYTBL.QSI_CONTROLNUM,			
QYTBL.QSI_SEQNUM,			
QYTBL.QSI_ORDERNUM,			
QYTBL.QSI_LOTNUM,			
QYTBL.QSI_LOTSIZE,			
QYTBL.QSI_SMPLSIZE,			
QYTBL.QSI_UNITS,			
QYTBL.QSI_COST,			
QYTBL.QSI_DATE,			
QYTBL.QSI_DATECONV,			
QYTBL.QSI_NAME,			
QYTBL.QSI_DN,			
QYTBL.QSI_CN,			
QYTBL.QSI_TEXT1,			
QYTBL.QSI_TEXT2,			
QYTBL.QSI_TEXT3,			
QYTBL.QSI_TEXT4,			
QYTBL.QSI_TEXT5,			
QYTBL.QSI_TEXT6,			
QYTBL.QSI_TEXT7,			
QYTBL.QSI_TEXT8,			
QYTBL.QSI_TEXT9,			
QYTBL.QSI_TEXT10,			
QYTBL.QSI_TEXT11,			
QYTBL.QSI_TEXT12,			
QYTBL.QSI_DESC1,			
QYTBL.QSI_DESC2		
FROM 				
QSI_SU_MD_LOOKUP QYTBL	


