--DROP VIEW CPRO_STG.QSI_KEYWORD_LOOKUP;

--CREATE OR REPLACE VIEW DANA_QSI_KEYWORD_LOOKUP
--AS 
SELECT 			
	ALL_KEY_ORG.QSI_KEY QSI_KEY, 			
	ALL_KEY_ORG.QSI_ORG QSI_ORG, 			
	CASE					
	WHEN EXACT_ORG.QSI_VALUE IS NULL THEN ALL_ORG.QSI_VALUE				
	ELSE EXACT_ORG.QSI_VALUE 			
	END 			QSI_VALUE		
	FROM 			
		( SELECT DISTINCT IC.FFPARAMETER_KEY QSI_KEY, O.QSI_KEY QSI_ORG 			  
			FROM FB_QSI_INFO_CAT_QY IC,  QSI_ORG_LOOKUP O			  
			WHERE	IC.FBROWID=0 AND IC.FFPARAMETER_TYPE='qsi_Keywords' AND	IC.FFQSI_LANGUAGE ='qsi_default'			
		) ALL_KEY_ORG		
	LEFT JOIN			
		( SELECT DISTINCT IC.FFPARAMETER_KEY QSI_KEY, IC.FFPARAMETER_NAME QSI_VALUE			  
			FROM FB_QSI_INFO_CAT_QY IC			  
			WHERE IC.FBROWID =0 AND	IC.FFPARAMETER_TYPE= 'qsi_Keywords' AND IC.FFQSI_LANGUAGE = 'qsi_default' AND IC.FFORGANIZATION = 'qsi_AllOrganizations'			
			) ALL_ORG 
	ON 	ALL_KEY_ORG.QSI_KEY = ALL_ORG.QSI_KEY		
	LEFT JOIN 			
		( SELECT IC.FFPARAMETER_KEY QSI_KEY, IC.FFPARAMETER_NAME QSI_VALUE, IC.FFORGANIZATION QSI_ORG
			FROM FB_QSI_INFO_CAT_QY IC 
			WHERE IC.FBROWID = 0 and IC.FFPARAMETER_TYPE='qsi_Keywords' AND	IC.FFQSI_LANGUAGE ='qsi_default' AND IC.FFORGANIZATION != 'qsi_AllOrganizations'			
			) EXACT_ORG 
	ON	ALL_KEY_ORG.QSI_KEY = EXACT_ORG.QSI_KEY